service: fastify

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
